### ISSUE TITLE
latest build please...

### ISSUE THREAD

**Issue by 0xh3LL0** [cqjjjzr/LCSELocalizationTools#1]
can you provide latest build release?

**Comment by cqjjjzr** [comment]
Sorry, but which util do you need? For the LCSEPackageUtility the latest build is in the Github Releases page.

As for the LCSESNXUtility.. Unfortunely I'm too lazy to write a command interface for it, so maybe you need to write code in the project and run it direct in the "LCSESNXUtilty" project.

apologize for that.

**Comment by 0xh3LL0** [comment]
because there is an error

![error](https://user-images.githubusercontent.com/23132217/65304182-3c0e3c80-dbaa-11e9-94a3-0b07bf1578a0.png)

![error2](https://user-images.githubusercontent.com/23132217/65304191-42041d80-dbaa-11e9-88d4-9b24a74cc982.png)

**Comment by cqjjjzr** [comment]
This is because you used the wrong command. you should use `java -jar LCSEPackageUtility-rv1.jar`

**Comment by 0xh3LL0** [comment]
whoops, my bad.
