### ISSUE TITLE
Error: Unable to access jarfile .\LCSEPackageUtility-rv1.jar

### ISSUE THREAD

**Issue by silverbulletgrz** [cqjjjzr/LCSELocalizationTools#3]
I plug the sample command included in the readme in to the command prompt but I get the a message saying Error: Unable to access jarfile .\LCSEPackageUtility-rv1.jar. I'm not familiar with this software environment, but does it have something to do with the absence of the actual .jar file in the downloads? 
If it helps, I'm using this to get Koihime Muso to run on my Windows 10 device. 

![image](https://user-images.githubusercontent.com/69591136/90029880-f68cbd80-dced-11ea-9611-1ff2b1b49415.png)

**Comment by cqjjjzr** [comment]
You should `cd` to the folder where the downloaded .jar file is located first.

**Comment by silverbulletgrz** [comment]
This is probably a silly question but which folder would that be? I don't spot a .jar file anywhere in the available downloads.

**Comment by cqjjjzr** [comment]
https://github.com/cqjjjzr/LCSELocalizationTools/releases/tag/pkgutil-rv1

**Comment by silverbulletgrz** [comment]
Ahh I downloaded the code instead of the actual .jar. My apologies and thanks.
