### ISSUE TITLE
I don't know Kotlin. Can you change the next version of keyIndex and keySNX to exe and let them be entered by yourself? This is friendly to people who don't understand source code recompilation

### ISSUE THREAD

**Issue by wycstc353** [cqjjjzr/LCSELocalizationTools#6]
I don't know Kotlin. Can you change the next version of keyIndex and keySNX to exe and let them be entered by yourself? This is friendly to people who don't understand source code recompilation

我不懂Kotlin，你能不能把keyIndex和keySNX下个版本改成exe并且让这两项可以自己输入呢，这样对不懂源码重新编译的人比较友好

**Comment by cqjjjzr** [comment]
改exe不太行，我个人不太想用 exe4j/launch4j 之类的工具

我后面会加个参数处理 key……其实还有字符编码的问题，都会在下个版本处理

**Comment by wycstc353** [comment]
> 改exe不太行，我个人不太想用 exe4j/launch4j 之类的工具
> 
> 我后面会加个参数处理 key……其实还有字符编码的问题，都会在下个版本处理

好的，有参数能自己加就好，话说这个引擎是必须封回lcsebody1里吗？不能像别的引擎一样弄个2的吗？话说现在有做了SNX转容易编辑的文本的功能吗？

**Comment by cqjjjzr** [comment]
。。刚刚看了下 早就加了参数啊……只是没有写进文档里。已经更新了 README 了。从 Release 下最新的 rv3 试试。

我自己写的确实只能封进 `lcsebody1`，不能弄 2。也没精力钻研这方面了。然后 SNX 转 gettext po 文件的在 `LCSESNXUtility` 文件夹。但那个没有做命令行界面，调用的代码在 https://github.com/cqjjjzr/LCSELocalizationTools/blob/master/LCSESNXUtility/src/main/kotlin/charlie/lcsetools/snxutil/BatchRunner.kt 和 https://github.com/cqjjjzr/LCSELocalizationTools/tree/master/LCSESNXUtility/src/test/kotlin/charlie/lcsetools/snxutil 且不是一般的混乱，还有编码的问题（写死了 Shift-JIS 到 GBK）……我都是用到哪里直接改代码调用的，可能确实得会一点点 Kotlin。

刚刚看了下，还有这三个文件 因为太过于破碎没有传进代码树，将就看看吧……近期确实是没有精力做这个

[snxutil.zip](https://github.com/cqjjjzr/LCSELocalizationTools/files/9626995/snxutil.zip)

**Comment by wycstc353** [comment]
> 。。刚刚看了下 早就加了参数啊……只是没有写进文档里。已经更新了 README 了。从 Release 下最新的 rv3 试试。
> 
> 我自己写的确实只能封进 `lcsebody1`，不能弄 2。也没精力钻研这方面了。然后 SNX 转 gettext po 文件的在 `LCSESNXUtility` 文件夹。但那个没有做命令行界面，调用的代码在 https://github.com/cqjjjzr/LCSELocalizationTools/blob/master/LCSESNXUtility/src/main/kotlin/charlie/lcsetools/snxutil/BatchRunner.kt 和 https://github.com/cqjjjzr/LCSELocalizationTools/tree/master/LCSESNXUtility/src/test/kotlin/charlie/lcsetools/snxutil 且不是一般的混乱，还有编码的问题（写死了 Shift-JIS 到 GBK）……我都是用到哪里直接改代码调用的，可能确实得会一点点 Kotlin。
> 
> 刚刚看了下，还有这三个文件 因为太过于破碎没有传进代码树，将就看看吧……近期确实是没有精力做这个
> 
> [snxutil.zip](https://github.com/cqjjjzr/LCSELocalizationTools/files/9626995/snxutil.zip)
解包代码这写得有问题吗
解包代码
java -jar .\LCSEPackageUtility-rv3.jar --unpack --list lcsebody1.lst --package lcsebody1 -s -d "F:\asdasd\6\Liquid\saiminryoujoku\patched" --key 0x02020202


封包代码
java -jar .\LCSEPackageUtility-rv3.jar --patch --patch-dir "D:\mugen\patches" --list lcsebody1.lst --package lcsebody1 -s -d "F:\asdasd\6\Liquid\saiminryoujoku\patched" --0x02020202

![image](https://user-images.githubusercontent.com/39401653/191951820-b11ee146-e5a4-43f3-9048-84a407820e9f.png)
![image](https://user-images.githubusercontent.com/39401653/191951885-7f9a16ca-1317-42b2-9667-3b3383dc0561.png)

**Comment by wycstc353** [comment]
![Uploading image.png…]()
0x01010101也试过一样的

**Comment by cqjjjzr** [comment]
……我都说了啊 `key` 和 `keySNX` 是 2 位 16 进制数，也就是 `--key 02` 这样的

**Comment by wycstc353** [comment]
![image](https://user-images.githubusercontent.com/39401653/191952483-f33f2714-6ad2-4fda-bbfe-2e58652a4c5c.png)

**Comment by wycstc353** [comment]
java -jar .\LCSEPackageUtility-rv3.jar --unpack --list lcsebody1.lst --package lcsebody1 -s -d "F:\asdasd\6\Liquid\saiminryoujoku\patched" --key 01
导出来了，但结果好像不对？同一个A000.snx，我用GARbro导出来的用日文编码能看到对话文本，用代码导出来是乱码，无论中文编码还是日文编码都是乱码

**Comment by cqjjjzr** [comment]
那就带 `--key-snx 00` 探测一下 SNX 文件的密钥，然后再用 `--key-snx 你找出来的密钥`

**Comment by wycstc353** [comment]
完蛋，第一个字节不会找……

**Comment by cqjjjzr** [comment]
先用 00 当密钥解出来一个 SNX，然后看看里面最多的字节就是真正的密钥

**Comment by wycstc353** [comment]
看了一下，03最多，可用03解还是不对……，哎

**Comment by cqjjjzr** [comment]
你用的啥命令 现在

**Comment by wycstc353** [comment]
java -jar .\LCSEPackageUtility-rv3.jar --unpack --list lcsebody1.lst --package lcsebody1 -s -d "F:\asdasd\6\Liquid\saiminryoujoku\patched" --key 01 --key-snx 03
解包，我发个用00解包的snx给你看下，

**Comment by wycstc353** [comment]
在 2022-09-23 20:02:19，"Charlie Jiang" ***@***.***> 写道：

你用的啥命令 现在

**Comment by wycstc353** [comment]
用邮件那你发你了，git我不会发附件

**Comment by cqjjjzr** [comment]
我最近都没在整这个了……可能这游戏用的格式已经变了，我也不一定能搞出来。

你的文件也没有发出来，Git要发附件直接打成zip就可以拖进评论框。邮件发的附件是收不到的。

另外请不要连续发comment……所有话尽量在一条说完，实在要加就用编辑功能。

**Comment by wycstc353** [comment]
[patched.zip](https://github.com/cqjjjzr/LCSELocalizationTools/files/9633474/patched.zip)
用00解包出来的，游戏格式应该没变，我解包的游戏也不算最近的了，催眠凌辱学園，2008年的游戏，别是我那个游戏太老？

**Comment by cqjjjzr** [comment]
就是 03 啊……你发发你用 03 解出来的？

**Comment by wycstc353** [comment]
[patched1.zip](https://github.com/cqjjjzr/LCSELocalizationTools/files/9633514/patched1.zip)
03jie解的

**Comment by cqjjjzr** [comment]
。。。原来是我以前写的代码有bug

已经发了新版了，下下来试试（rv4）

**Comment by wycstc353** [comment]
嗯，可以了，导出和导入都试了，原版没改的导入和导出都没问题了，之后我再慢慢试改编码和对话试试

**Comment by cqjjjzr** [comment]
对话就去研究下LCSESNXUtility里的代码吧……我都忘了当时怎么写的调用代码了
